---
version: '2.4'
services:
  rabbit:
    extends:
      file: docker-compose.yml
      service: rabbit
    networks:
      - net_rabbit_bridge_transfer
      - net_rabbit_bridge_convert_to_chai_worker
  redis:
    extends:
      file: docker-compose.yml
      service: redis
    networks:
      - net_db_bridge_transfer
  bridge_request:
    extends:
      file: docker-compose.yml
      service: bridge_request
    networks:
      - net_db_bridge_request
      - net_rabbit_bridge_request
  bridge_collected:
    extends:
      file: docker-compose.yml
      service: bridge_collected
    volumes:
      - '~/bridge_data/access-lists/block_list.txt:/mono/oracle/access-lists/block_list.txt'
      - '~/bridge_data/access-lists/allowance_list.txt:/mono/oracle/access-lists/allowance_list.txt'
    networks:
      - net_db_bridge_request
      - net_rabbit_bridge_request
  bridge_affirmation:
    extends:
      file: docker-compose.yml
      service: bridge_affirmation
    networks:
      - net_db_bridge_request
      - net_rabbit_bridge_request
  bridge_transfer:
    cpus: 0.1
    mem_limit: 500m
    image: poanetwork/tokenbridge-oracle:latest
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - ORACLE_VALIDATOR_ADDRESS=${ORACLE_VALIDATOR_ADDRESS}
    restart: unless-stopped
    entrypoint: yarn watcher:transfer
    networks:
      - net_db_bridge_transfer
      - net_rabbit_bridge_transfer
  bridge_convert_to_chai_worker:
    cpus: 0.1
    mem_limit: 500m
    image: poanetwork/tokenbridge-oracle:latest
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - ORACLE_VALIDATOR_ADDRESS=${ORACLE_VALIDATOR_ADDRESS}
    restart: unless-stopped
    entrypoint: yarn worker:convert-to-chai
    networks:
      - net_rabbit_bridge_convert_to_chai_worker
  bridge_senderhome:
    extends:
      file: docker-compose.yml
      service: bridge_senderhome
    networks:
      - net_db_bridge_request
      - net_rabbit_bridge_request
  bridge_senderforeign:
    extends:
      file: docker-compose.yml
      service: bridge_senderforeign
    networks:
      - net_db_bridge_request
      - net_rabbit_bridge_request

networks:
  net_db_bridge_request:
    driver: bridge
  net_db_bridge_collected:
    driver: bridge
  net_db_bridge_affirmation:
    driver: bridge
  net_db_bridge_transfer:
    driver: bridge
  net_db_bridge_senderhome:
    driver: bridge
  net_db_bridge_senderforeign:
    driver: bridge
  net_rabbit_bridge_request:
    driver: bridge
  net_rabbit_bridge_collected:
    driver: bridge
  net_rabbit_bridge_affirmation:
    driver: bridge
  net_rabbit_bridge_transfer:
    driver: bridge
  net_rabbit_bridge_senderhome:
    driver: bridge
  net_rabbit_bridge_senderforeign:
    driver: bridge
  net_rabbit_bridge_convert_to_chai_worker:
    driver: bridge
