---
version: '2.4'
services:
  rabbit:
    extends:
      file: docker-compose.yml
      service: rabbit
    networks:
      - net_rabbit_bridge_transfer
      - net_rabbit_bridge_half_duplex_transfer
      - net_rabbit_bridge_swap_tokens_worker
      - net_rabbit_bridge_convert_to_chai_worker
  redis:
    extends:
      file: docker-compose.yml
      service: redis
    networks:
      - net_db_bridge_transfer
      - net_db_bridge_half_duplex_transfer
  bridge_request:
    extends:
      file: docker-compose.yml
      service: bridge_request
    networks:
      - net_db_bridge_request
      - net_rabbit_bridge_request
  bridge_collected:
    extends:
      file: docker-compose.yml
      service: bridge_collected
    networks:
      - net_db_bridge_request
      - net_rabbit_bridge_request
  bridge_affirmation:
    extends:
      file: docker-compose.yml
      service: bridge_affirmation
    networks:
      - net_db_bridge_request
      - net_rabbit_bridge_request
  bridge_transfer:
    cpus: 0.1
    mem_limit: 500m
    build:
      context: ..
      dockerfile: oracle/Dockerfile
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - ORACLE_VALIDATOR_ADDRESS=${ORACLE_VALIDATOR_ADDRESS}
    restart: unless-stopped
    entrypoint: yarn watcher:transfer
    networks:
      - net_db_bridge_transfer
      - net_rabbit_bridge_transfer
  bridge_half_duplex_transfer:
    cpus: 0.1
    mem_limit: 500m
    build:
      context: ..
      dockerfile: oracle/Dockerfile
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - ORACLE_VALIDATOR_ADDRESS=${ORACLE_VALIDATOR_ADDRESS}
    restart: unless-stopped
    entrypoint: yarn watcher:half-duplex-transfer
    networks:
      - net_db_bridge_half_duplex_transfer
      - net_rabbit_bridge_half_duplex_transfer
  bridge_swap_tokens_worker:
    cpus: 0.1
    mem_limit: 500m
    build:
      context: ..
      dockerfile: oracle/Dockerfile
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - ORACLE_VALIDATOR_ADDRESS=${ORACLE_VALIDATOR_ADDRESS}
    restart: unless-stopped
    entrypoint: yarn worker:swap-tokens
    networks:
      - net_rabbit_bridge_swap_tokens_worker
  bridge_convert_to_chai_worker:
    cpus: 0.1
    mem_limit: 500m
    build:
      context: ..
      dockerfile: oracle/Dockerfile
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - ORACLE_VALIDATOR_ADDRESS=${ORACLE_VALIDATOR_ADDRESS}
    restart: unless-stopped
    entrypoint: yarn worker:convert-to-chai
    networks:
      - net_rabbit_bridge_convert_to_chai_worker
  bridge_senderhome:
    extends:
      file: docker-compose.yml
      service: bridge_senderhome
    networks:
      - net_db_bridge_request
      - net_rabbit_bridge_request
  bridge_senderforeign:
    extends:
      file: docker-compose.yml
      service: bridge_senderforeign
    networks:
      - net_db_bridge_request
      - net_rabbit_bridge_request

networks:
  net_db_bridge_request:
    driver: bridge
  net_db_bridge_collected:
    driver: bridge
  net_db_bridge_affirmation:
    driver: bridge
  net_db_bridge_transfer:
    driver: bridge
  net_db_bridge_half_duplex_transfer:
    driver: bridge
  net_db_bridge_senderhome:
    driver: bridge
  net_db_bridge_senderforeign:
    driver: bridge
  net_rabbit_bridge_request:
    driver: bridge
  net_rabbit_bridge_collected:
    driver: bridge
  net_rabbit_bridge_affirmation:
    driver: bridge
  net_rabbit_bridge_transfer:
    driver: bridge
  net_rabbit_bridge_half_duplex_transfer:
    driver: bridge
  net_rabbit_bridge_swap_tokens_worker:
    driver: bridge
  net_rabbit_bridge_senderhome:
    driver: bridge
  net_rabbit_bridge_senderforeign:
    driver: bridge
  net_rabbit_bridge_convert_to_chai_worker:
    driver: bridge
