# This role creates a tokenbridge-monitor service which is designed to manage docker-compose monitor deployment.
# /etc/init.d/tokenbridge-monitor start, status, stop, restart - does what the services usually do in such cases.
# /etc/init.d/tokenbridge-monitor rebuild - builds a new monitor deployment from scratch.
---
- name: "Set the service"
  template:
    src: tokenbridge-monitor.j2
    dest: "/etc/init.d/tokenbridge-monitor"
    owner: root
    mode: 755
    
- name: "Start/Enable the service"
  service:
    name: "tokenbridge-monitor"
    state: started
    enabled: yes
    use: service
