- name: Slurp docker compose file
  slurp:
    src: "{{ bridge_path }}/oracle/docker-compose.yml"
  register: docker_compose_slurp

- name: Parse docker compose file
  set_fact: 
    docker_compose_parsed: "{{ docker_compose_slurp['content'] | b64decode | from_yaml }}"

- name: Set logger to remote server
  set_fact:
    docker_compose_parsed: "{{ docker_compose_parsed |combine({'services': {item: {'logging': {'driver': 'syslog','options': {'tag': '{{.Name}}/{{.ID}}'}}}}}, recursive=True) }}"
  with_items: "{{ docker_compose_parsed.services }}"
   
- name: Write new docker-compose file
  copy:
    content: "{{ docker_compose_parsed | to_yaml }}"
    dest: "{{ bridge_path }}/oracle/docker-compose.yml"

- name: Set the local container logs configuration file
  template:
    src: 31-oracle-docker.conf.j2
    dest: /etc/rsyslog.d/31-oracle-docker.conf
    owner: root
    group: root
    mode: 0644

- name: Set the log configuration file to send container logs to remote server
  template:
    src: 36-oracle-remote-logging.conf.j2
    dest: /etc/rsyslog.d/36-oracle-remote-logging.conf
    owner: root
    group: root
    mode: 0644
  when: syslog_server_port is defined

- name: Discarding unwanted messages in rsyslog
  blockinfile:
    path: /etc/rsyslog.conf
    insertbefore: "# Where to place spool and state files"
    marker: "#{mark} add string to discarding unwanted messages"
    content: ':msg, contains, "VALIDATOR_ADDRESS_PRIVATE_KEY" ~'
  notify: restart rsyslog
