---
- name: Create oracle directory
  file:
    path: "{{ bridge_path }}/oracle"
    state: directory
    mode: '0755'

- name: Install .env config
  template:
    src: .env.j2
    dest: "{{ bridge_path }}/oracle/.env"
    owner: "{{ compose_service_user }}"
    mode: '0640'

- name: Copy docker-compose files
  copy:
    src: ../../../../oracle/{{ item }}
    dest: "{{ bridge_path }}/oracle/"
    mode: '0755'
  with_items:
    - docker-compose.yml
    - docker-compose-transfer.yml
    - docker-compose-erc-native.yml
